name: CI
on:
  push:
      branches: [master]
      path_ignore:
          - '**/README.md'
  
  workflow_dispatch:

jobs:
  build:
    name: flutter build webview
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5"
      - run: dart script.dart --url=${{secrets.URL}} -key-password=${{secrets.KEY_PASSWORD}} --key-store-password=${{secrets.STORE_PASSWORD}} --key-alias=upload --key-store-path --key-store=${{secrets.KEY_STORE}}
      - run: flutter pub get
      # - run: flutter build ipa --debug
      - run: flutter build apk
      - uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GH_TOKEN }}
          tag: "1.0.2"
          commit: ${{ github.sha }}