name: CI
on:
  push:
      branches: [master]
      path_ignore:
          - '**/README.md'
  
  workflow_dispatch:

jobs:
  build:
    name: flutter build webview
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5"
      - run: echo "{\"url\":\"https://google.com\"}" > assets/assets.json
      - run: flutter pub get
      - run: flutter build ios --no-codesign
      - uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/"
          token: ${{ secrets.GH_TOKEN }}
          tag: "1.0.1"
          commit: ${{ github.sha }}